# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg484-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/bm_noisegen_xilinx/bm_noisegen_xilinx.cache/wt} [current_project]
set_property parent.project_path {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/bm_noisegen_xilinx/bm_noisegen_xilinx.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog {
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/bm_constants.vh}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/fixedpt_funcs.vh}
}
set_property file_type "Verilog Header" [get_files {{C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/bm_constants.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/fixedpt_funcs.vh}}]
read_verilog -library xil_defaultlib {
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/cordic_circular.v}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/cordic_hyperb.v}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/sqrtunit.v}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/tauss.v}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/sincos.v}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/logunit.v}
  {C:/work/SCU/CourseWork/PhD courses/ELEN 249 - Topics in communication/project_2/temp/Verilog/test8/bm_noisegen/bm_noisegen.v}
}
synth_design -top bm_noisegen -part xc7k70tfbg484-3
write_checkpoint -noxdef bm_noisegen.dcp
catch { report_utilization -file bm_noisegen_utilization_synth.rpt -pb bm_noisegen_utilization_synth.pb }
